### PR TITLE
Fix `helpstr_` erroing on shell syntax

### LINKED ISSUE #40: `helpstr_` doesn't quote inputs or handle shell error
For example, running

    help=(

Causes a segfault in `fsclient` or `boss`, depending on running with fs server or not:

```
23:16:14;help=(
sh: 1: Syntax error: "(" unexpected
sh: 1: Syntax error: "(" unexpected

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
...
boss terminated-Segmentation violation
```

This was the underlying problem in #3.

The shell use allows some pretty trivial remote execution. While it's not security issue right now as we "trust" user input, it might be good to fix this if we want to change model in the future. 

In a similar vein, there's also a buffer overrun error here that should be fixed.

### PR DESCRIPTION
**Pull request by dehorsley**
This removes the call to `system` in clib/helpstr used to list contents for fs/help and st/help starting with the user provided prefix, instead opting to list the directories directly with C routines. 

This routine is used by boss and fsclient.

This pr also removed a couple of potential buffer overruns in helpstr, although one still exist as helpstr does not check bounds of the buffer provided for output. I think this will require a signature change.

The main "business" logic was left unchanged.

It does use dynamic memory which we typically try to avoid in clib, but I have run it through valgrind and it looks like there are no leaks.

Fixes #40

### CODE REVIEW

**Comment by dehorsley** [comment]
Mostly I wanted you to cast your eyes over this Ed as it's somewhat of a large change.

It's otherwise tested and good to go.

File: fsserver/fsclient.c [hunk 1]
```diff
@@ -17,12 +17,12 @@
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
  */
-#define _GNU_SOURCE
```
Comment (wehimwich) [inline fsserver/fsclient.c:20]: This deleted line seems to be needed on FSL10 amd64.

File: clib/helpstr.c [hunk 2]
```diff
@@ -26,13 +27,92 @@
...
+		while ((ep = readdir(dp))) {
+			if (strncmp(prefix, ep->d_name, prefix_len) != 0) {
+				continue;
+			}
+
+			nmatches++;
+
+			if (nmatches > len) {
+				len += len;
+				ret = realloc(ret, len + 1);
```
Comment (wehimwich) [inline clib/helpstr.c:104]: Should this be something like:
````
-                              ret = realloc(ret, len + 1);
+                              ret = realloc(ret, (len + 1) * sizeof(char *));
+                              int i;
+                              for (i=len/2;i<=len;i++)
+                                  *ret[i]=0;
 ````

File: clib/helpstr.c [hunk 3]
```diff
@@ -43,115 +123,107 @@ int *ierr;
...
+	if (decloc != NULL) {
+		char *p = check_help_dirs(name);
+		if (p == NULL) {
+			return;
+		}
+		*ierr = 0;
+		strcpy(runstr, p);
+		free(p);
+		return;
+	}
```
Comment (wehimwich) [inline clib/helpstr.c:150]: It is complicated to get that old time behavior.

File: clib/helpstr.c [hunk 4]
```diff
@@ -43,115 +123,107 @@ int *ierr;
...
+
+	char **p;
+	for (p = paths; *p != NULL; p++) {
+		char *path = *p;
+		decloc     = strrchr(path, '.');
+		if (decloc == NULL) {
+			continue;
+		}
```
Comment (wehimwich) [inline clib/helpstr.c:163]: Again. :)

File: clib/helpstr.c [hunk 5]
```diff
@@ -26,13 +27,92 @@
...
+#define MAX_STRING 256
+
+// fileexists check if file exists and is readable
+static int fileexists(const char *filename) {
+	FILE *file;
+	if ((file = fopen(filename, "r"))) {
+		fclose(file);
+		return 1;
+	}
+	return 0;
```
Comment (wehimwich) [inline clib/helpstr.c:49]: Maybe:

````
-       if ((file = fopen(filename, "r"))) {
-               fclose(file);
-               return 1;
-       }
-       return 0;
+       if (access(filename, R_OK))
+           return 0;
+
+       return 1;
````

**Comment by wehimwich** [comment]
Late breaking nows. I tried help for command (bbc01) not supported by the current equipment (mk3), I got:

> 21:59:32;help=bbc01
> *** Error in `boss': double free or corruption (out): 0x000055debbc5e270 ***
> ======= Backtrace: =========
> /lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7f34f278cbfb]
> /lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7f34f2792fc6]
> /lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7f34f279380e]
> /lib/x86_64-linux-gnu/libc.so.6(vasprintf+0x12c)[0x7f34f278bc0c]
> /lib/x86_64-linux-gnu/libc.so.6(asprintf+0x87)[0x7f34f276b3e7]
> boss(+0x29bb8)[0x55debaaadbb8]
> boss(+0x29d39)[0x55debaaadd39]
> boss(+0xb2b5)[0x55debaa8f2b5]
> boss(+0xa285)[0x55debaa8e285]
> boss(+0x229f)[0x55debaa8629f]
> boss(+0x22fe)[0x55debaa862fe]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f34f273c2e1]
> boss(+0x209a)[0x55debaa8609a]
> ======= Memory map: ========
> 55debaa84000-55debaabc000 r-xp 00000000 fd:09 24516625                   /usr2/fs-git/bin/boss
> 55debacbc000-55debacbd000 r--p 00038000 fd:09 24516625                   /usr2/fs-git/bin/boss
> 55debacbd000-55debacc0000 rw-p 00039000 fd:09 24516625                   /usr2/fs-git/bin/boss
> ...

This was with the latest commit (but fsclient fixed, but server is disabled) on the pr.

**Comment by dehorsley** [comment]
Ohf.  I'll see if I can reproduce that on my VM here. Just triggered with

    help=bbc

?

File: clib/helpstr.c (hunk 5 above)
Comment (dehorsley) [reply clib/helpstr.c:49]: Ooh nice I didn't know about that one. We should be able to remove this routine altogether.

**Comment by wehimwich** [comment]
help=bbc01

File: fsserver/fsclient.c (hunk 1 above)
Comment (dehorsley) [reply fsserver/fsclient.c]: Ah that landed in there too early, I have moved that to the fsserver Makefile on another branch. 

Reverted for now.

**Comment by dehorsley** [comment]
Ok looks like that crash was due to the wrong size given to `realloc`. Looks like it's fixed now

File: clib/helpstr.c (hunk 2 above)
Comment (dehorsley) [reply clib/helpstr.c]: Or even

    -    *ret[i]=0;
    +    ret[i]=0;

This programming business is hard.

File: clib/helpstr.c [hunk 6]
```diff
@@ -43,115 +125,107 @@ int *ierr;
...
+		if (p == NULL) {
+			return;
+		}
+		*ierr = 0;
+		strcpy(runstr, p);
+		free(p);
+		return;
+	}
+
+	char **paths = ls_prefix(help_dirs, name);
```
Comment (wehimwich) [inline clib/helpstr.c:154]: I noticed that **help=vc**, apparently picks whatever **vcxx** it happens to hit first in the directory. There can also be less related prefix matches. Unless you intend this behavior I think it can be prevented adding

strcat(name,".",1); 

just before this line. Or to be "safe" maybe something ugly like:

strncat(name,".",sizeof(name)-strlen(name) < 2 ? 0 : 1);

Comment (dehorsley) [reply clib/helpstr.c:154]: Good point

File: clib/helpstr.c [hunk 7]
```diff
@@ -43,115 +125,107 @@ int *ierr;
...
+		*ierr = -2;
+		return;
+	}
+
+	strncpy(name, cnam, *clength);
+	name[*clength] = '\0';
+
+	decloc = strchr(name, '.');
+	if (decloc != NULL) {
+		char *p = check_help_dirs(name);
```
Comment (dehorsley) [inline clib/helpstr.c:144]: I think this actually does more than advertised. Eg giving it the argument `../../etc/passwd`, it will return successfully. It might be easier to restore the method the old code used, of appending "." if not present

Comment (wehimwich) [reply clib/helpstr.c:144]: Sort of symmetric with other case I guess. I think you are saying that it could branch out of the directory and display some other file entirely. That seems like it would be safe, but might have some unpleasant effect if the file is binary. Maybe it should be rejected if the first character is dot and if the first dot isn't the last minus third(?) character (making it conform to the expected format). I suppose the old code had this defect as well. Or have I gone down a rabbit hole. :)

**Comment by dehorsley** [comment]
> Is there some way to contribute a commit to a PR? I wasn't sure I could do that without merging the whole thing back.

Yup you can push to this branch to update the PR. 

If you're using [hub](https://hub.github.com/) it makes it a log easier:

    git pr checkout 41

> If would be good if the message identifies the routine where the error was generated (it is probably too hard to make sure the message is unique across the whole FS otherwise, but it should be unique within the routine anyway). Even better would be if it also identified the program where it occurred. However, just not failing silently is a big improvement; a lot of these errors are "unlikely" anyway.

Checkout the `fatal` macro I use in  [fsserver/fsclient.c#L56](https://github.com/nvi-inc/fs/blob/1259ff19f339721389ff5a63c2a0546c7b602596/fsserver/fsclient.c#L56). 

It prints the procedure and line number were there error occurred, which is a huge help. Getting the program name might require setting the name put in a global variable.

File: clib/helpstr.c (hunk 7 above)
Comment (dehorsley) [reply clib/helpstr.c:144]: I was more thinking down-the-line we might like to expose this function to a user who shouldn't be able to list any file. 

The prefix case is safe from directory traversal, as it lists the directory contents of the help directories directly. That's why I wanted to reduce this case to the prefix one.

Comment (wehimwich) [reply clib/helpstr.c:144]: Not quite sure what you are getting at about down the line, but I made a mistake in the call to access, it should be:
````
		if ( ! access(path, R_OK)) {
			return path;
		}
````
Sorry about that. With that, it rejects **help=../../etc/passwd**, but branches out for **help=../../../etc/passwd**, which of course is a problem, back to my first reply. I can look at that later if you haven't.

Comment (dehorsley) [reply clib/helpstr.c:147]: Fixed the inverted logic. I went with just adding a check at the top for a "/" in the name and aborting.

File: clib/helpstr.c (hunk 6 above)
Comment (dehorsley) [reply clib/helpstr.c:161]: OK, I just made sure the stack buffer was big enough to fit the null byte and the potential '.'

I'm always wary of the `strn*` functions; they never seem to do quite what I expect them to do and I have to think to hard when I re-read the code.

**Comment by dehorsley** [comment]
OK, now I think it's done, unless you have anything to add?

I suggest we squash and merge this — too many noisy commits. We always have this thread for history.
